name: AnarchiaCore
main: me.anarchiacore.AnarchiaCorePlugin
version: 1.0.0
api-version: 1.21
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
permissions:
  anarchiacore.admin:
    default: op
    children:
      anarchiacore.admin.dripstone: true
  anarchiacore.admin.dripstone:
    default: op
