name: AnarchiaCore
main: me.anarchiacore.AnarchiaCorePlugin
version: 1.0.0
api-version: 1.21
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
commands:
  anarchiacore:
    aliases: [acore, anarchia]
  antylogout:
    aliases: [combatlog]
  kosz:
    aliases: [trash, bin]
  stormitemy:
    aliases: [stormitems]
  menuprzedmioty:
    aliases: [przedmioty]
permissions:
  anarchiacore.admin:
    default: op
    children:
      anarchiacore.admin.dripstone: true
  anarchiacore.admin.dripstone:
    default: op
